def tell_joke(joke, answer):
  print(joke)
  user_input = input("What's your answer? ")
  if user_input == answer:
    print("Good job! You got the joke.")
  else:
    print("Sorry, the answer is " + answer)

tell_joke("What do you call a fish with no eyes? Fsh!", "Fsh!")
tell_joke("Why did the scarecrow win an award? Because he was outstanding in his field!", "outstanding in his field!")
tell_joke("Why did the bicycle fall over? Because it was two tired!", "two tired!")
tell_joke("What do you call a lazy kangaroo? A pouch potato!", "pouch potato!")
tell_joke("Why did the coffee go to the police? Because it got mugged!", "got mugged!")

# More jokes

tell_joke("What do you call a cow with no legs? Ground beef!", "Ground beef!")
tell_joke("Why did the golfer wear two pairs of pants? In case he got a hole in one!", "hole in one!")
tell_joke("What do you call a fish with no eyes? Fsh!", "Fsh!")
tell_joke("Why did the scarecrow win an award? Because he was outstanding in his field!", "outstanding in his field!")
tell_joke("Why did the bicycle fall over? Because it was two tired!", "two tired!")
tell_joke("What do you call a lazy kangaroo? A pouch potato!", "pouch potato!")
tell_joke("Why did the coffee go to the police? Because it got mugged!", "got mugged!")
tell_joke("What do you call a cow with no legs? Ground beef!", "Ground beef!")
tell_joke("Why did the golfer wear two pairs of pants? In case he got a hole in one!", "hole in one!")
tell_joke("What do you call a fish with no eyes? Fsh!", "Fsh!")
tell_joke("Why did the scarecrow win an award? Because he was outstanding in his field!", "outstanding in his field!")
tell_joke("Why did the bicycle fall over? Because it was two tired!", "two tired!")
tell_joke("What do you call a lazy kangaroo? A pouch potato!", "pouch potato!")
tell_joke("Why did the coffee go to the police? Because it got mugged!", "got mugged!")
tell_joke("What do you call a cow with no legs? Ground beef!", "Ground beef!")
tell_joke("Why did the golfer wear two pairs of pants? In case he got a hole in one!", "hole in one!")
tell_joke("What do you call a fish with no eyes? Fsh!", "Fsh!")
tell_joke("Why did the scarecrow win an award? Because he was outstanding in his field!", "outstanding in his field!")
tell_joke("Why did the bicycle fall over? Because it was two tired!", "two tired!")
tell_joke("What do you call a lazy kangaroo? A pouch potato!", "pouch potato!")
tell_joke("Why did the coffee go to the police? Because it got mugged!", "got mugged!")
tell_joke("What do you call a cow with no legs? Ground beef!", "Ground beef!")
tell_joke("Why did the golfer wear two pairs of pants? In case he got a hole in one!", "hole in one!")
tell_joke("What do you call a fish with no eyes? Fsh!", "Fsh!")
tell_joke("Why did the scarecrow win an award? Because he was outstanding in his field!", "outstanding in his field!")
tell_joke("Why did the bicycle fall over? Because it was two tired!", "two tired!")
tell_joke("What do you call a lazy kangaroo? A pouch potato!", "pouch potato!")
tell_joke("Why did the coffee go to the police? Because it got mugged!", "got mugged!")
